#!/bin/sh

# Give a list of bookmarks to search and open them in current browser

choice=$(buku --stag star -x -f 3 | sed 's/\t/ /g' | dmenu -i -l 10)

# if nothing is chosen then exit
[ "$choice" != "" ] || exit

buku -o $choice
