#!/bin/sh

# EMOJIMENU
# Simon H Moore
# Got the original idea and copied some code from LukeSmith
# 
# Gives a list of emojies in dmenu and puts the character
# in the primary selection and clipboard. 
# Requires xclip and dmenu to work.

chosen=$(grep -v "#" ~/.config/emoji | dmenu -i -l 20)

[ "$chosen" != "" ] || exit

emoji=$(echo "$chosen" | awk '{print $1}')
echo "$emoji" | tr -d '\n' | xclip -f | xclip -sel clip
notify-send "$emoji copied to primary and clipboard." &
