#!/bin/sh

# EMOJIMENU
# Simon H Moore
# Got the original idea and copied some code from LukeSmith
# 
# Gives a list of emojis in dmenu and puts the character
# in the primary selection and clipboard. 
# Requires xclip and dmenu to work.

# location of file containing list of emojis
emoji_file=~/.config/emoji

# get chosen emoji from user using dmenu
chosen=$(grep -v "#" "$emoji_file" | dmenu -i -l 20) || exit

# get emoji character from chosen
emoji=$(echo "$chosen" | awk '{print $1}')

# put emoji character in both primary and clipboard selection
echo "$emoji" | tr -d '\n' | xclip -f | xclip -sel clip

# notify user of action
notify-send "$emoji copied to primary and clipboard." &
