#!/bin/sh
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in dunst if running.

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

chosen=$(cat ~/.config/font-awesome | dmenu -i -l 20)

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | awk '{print $1}')
echo "$c" | tr -d '\n' | xclip -selection clipboard
echo "$c"
notify-send "'$c' copied to clipboard." &

s=$(echo "$chosen" | awk '{print $3}')
echo "$s" | tr -d '\n' | xclip
echo "$s"
