#!/bin/sh

dir="$PDFS"

url=$(xclip -sel clip)

title=$(gethtmltitle "$url" | tr '[:upper:]' '[:lower:]' \
    | sed 's/&/ and /g;
            s/+/ plus /g;
            s/=/ equals /g;
            s/[[:punct:]]/ /g;
            s/[[:space:]]*-[[:space:]]*/-/g;
            s/[[:space:]][[:space:]]*/_/g;
            r/[^[:alnum:]_-]/g' \
    | dmenu -i -l 10 -p "for: ") || exit 1

htmltopdf "$url" "$dir/${title}.pdf"
