#!/bin/bash

# Dmenu to choose from poweroff, restart or logout

choices="hybernate\nexit\npoweroff\nreboot"

choice=$(echo -e "$choices" | dmenu -sb "#ad1616" -p "Quit Menu: ")

case "$choice" in 
    hybernate) sudo ZZZ;; 
    exit) killall xinit;;
    poweroff) sudo shutdown -h now & ;;
    reboot) sudo reboot & ;;
esac
