#!/bin/sh


# Gives a dmenu list of all files in the pdfs dir

shots_dir="$PICTURES/shots/"

# get choice of pdf
choice=$(ls -r $shots_dir | ddmenu -i -l 10)

# if nothing is chosen then exit
[ "$choice" != "" ] || exit

# open pdf using zathura
feh "$shots_dir/$choice"

