#!/bin/sh

# SHOTMENU
# Simon H Moore
# 
# Gives a list of screen shot options:
# Window: screen shot the currently focused window.
# Select: select and area with your mouse to screen shot.
# 
# Requires dmenu and shot to work.

choices="Window\nSelect"
prompt="Please choose:"

choice=$(echo "$choices" | dmenu -p "choose")

case "$choice" in 
    Window) shot -u && exit & ;;
    Select) shot -s && exit & ;;
esac
