#!/bin/sh

# Dmenu to choose window or select shot

choices="Window\nSelect"
prompt="Please choose:"

choice=$(echo "$choices" | dmenu -sb "#ad1616" -p "choose")

case "$choice" in 
    Window) shot -u && exit & ;;
    Select) shot -s && exit & ;;
esac
